version: '2.1'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4567-4582:4567-4582"
      - "8080:8080"
    environment:
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
    volumes:
      - "./data:/tmp/localstack"
    networks:
      - default
      - localstack_network

networks:
  localstack_network:
    external: true
